### ISSUE TITLE
Some text is nearly unreadable

### ISSUE THREAD

**Issue by ghost** [catppuccin/qterminal#1]
Certain dialogs (unfocused windows/subwindows, all VirtualBox text) lose all their contrast after applying the theme. I'm not sure what causes this, but it makes a several applications very hard to use.

**Comment by prateektade** [comment]
Sorry for the delay in responding.

Could you share some before/after screenshots to show what exactly happens? Reading the description, it seems a little confusing to me how a terminal emulator theme can affect colors of windows.

Also, you mentioned Virtualbox, so I wanted to know if you experienced this specifically in Virtualbox or on hardware too?

**Comment by ghost** [comment]
I'm sorry for the confusion. I don't know why I would open an issue on the Terminal emulator theme... Feel free to delete this
